# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-12-19 14:37+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: app/consts/i18n.py:9
msgid "Brazilian Portuguese"
msgstr "Português Brasileiro"

#: app/consts/i18n.py:10
msgid "English"
msgstr "Inglês"

#: app/consts/i18n.py:19
msgid "São Paulo - Brazil (-03:00)"
msgstr "São Paulo - Brasil (-03:00)"

#: app/consts/i18n.py:20
msgid "Universal Coordinated Time"
msgstr "Tempo Coordenado Universal (UTC)"

#: app/consts/push_notification.py:21
msgid "Created"
msgstr "Criado"

#: app/consts/push_notification.py:22
msgid "Enqueued"
msgstr "Na fila"

#: app/consts/push_notification.py:23
msgid "Sent"
msgstr "Enviado(a)"

#: app/consts/push_notification.py:24
msgid "Delivered"
msgstr "Entregue"

#: app/consts/push_notification.py:25
msgid "Read"
msgstr "Lido(a)"

#: app/consts/push_notification.py:26
msgid "Failed"
msgstr "Falhou"

#: app/consts/push_notification.py:43
msgid "Device not registered"
msgstr "Dispositivo não registrado"

#: app/consts/push_notification.py:44
msgid "Message too big"
msgstr "Mensagem muito grande"

#: app/consts/push_notification.py:45
msgid "Message rate exceeded"
msgstr "Limite de mensagens excedido"

#: app/consts/push_notification.py:46
msgid "Mismatch sender ID"
msgstr "ID remetente não confere"

#: app/consts/push_notification.py:47
msgid "Invalid credentials"
msgstr "Credenciais inválidas"

#: app/consts/push_notification.py:48
msgid "Not opted-in"
msgstr "Não permitiu"

#: app/consts/push_notification.py:49
msgid "Too many delivery attempts"
msgstr "Muitas tentativas de entrega"

#: app/consts/push_notification.py:58
msgid "Internal communication"
msgstr "Comunicação interna"

#: app/exceptions.py:13
msgid "Unexpected failure"
msgstr "Falha inesperada"

#: app/exceptions.py:33
msgid "Insufficient permissions"
msgstr "Permissões insuficientes"

#: app/forms/fields/phone.py:38
#, python-format
msgid "Invalid phone number. Original error message was: %s"
msgstr "Número telefone inválido. Mensagem de erro original: %s"

#: app/models/base.py:13
msgid "id"
msgstr "id"

#: app/models/base.py:91
msgid "created at"
msgstr "criado em"

#: app/models/base.py:94
msgid "updated at"
msgstr "atualizado em"

#: app/services.py:60
msgid "Request failed at"
msgstr "Requisição falhou em"

#: app/services.py:63 app/services.py:92
msgid "Exception class"
msgstr "Classe exceção"

#: app/services.py:64 app/services.py:93
msgid "More information available on the attached logs/traceback"
msgstr "Mais informações disponíveis nos logs/traceback anexados"

#: app/services.py:88
msgid "Task failed"
msgstr "Tarefa falhou"

#: app/services.py:89
msgid "Task id"
msgstr "Id tarefa"

#: app/services.py:90
msgid "Task args"
msgstr "Args tarefa"

#: app/services.py:91
msgid "Task kwargs"
msgstr "Kwargs tarefa"

#: app/validators/br/doc.py:35
msgid "Invalid Certificate"
msgstr "certificado inválido"

#: app/validators/br/doc.py:42
msgid "Invalid CNH"
msgstr "CNH inválida"

#: app/validators/br/doc.py:49
msgid "Invalid CNPJ"
msgstr "CNPJ inválido"

#: app/validators/br/doc.py:56
msgid "Invalid CNS"
msgstr "CNS inválido"

#: app/validators/br/doc.py:63
msgid "Invalid CPF"
msgstr "CPF inválido"

#: app/validators/br/doc.py:70
msgid "Invalid CPF/CNPJ"
msgstr "CPF/CNPJ inválido"

#: app/validators/br/doc.py:80
msgid "Invalid PIS"
msgstr "PIS inválido"

#: app/validators/br/doc.py:87
msgid "Invalid RENAVAM"
msgstr "RENAVAM inválido"

#: app/validators/br/doc.py:94
msgid "Invalid Voter Registration"
msgstr "Título Eleitoral inválido"

#: push_notifications/admin.py:48
msgid "Title"
msgstr "Título"

#: push_notifications/admin.py:60
msgid "Failure reason"
msgstr "Motivo de falha"

#: push_notifications/admin.py:73
msgid "Delivery"
msgstr "Entrega"

#: push_notifications/admin.py:76 users/admin.py:46
msgid "Metadata"
msgstr "Meta-dados"

#: push_notifications/apps.py:8
msgid "Push Notification"
msgstr "Notificação Push"

#: push_notifications/apps.py:9
msgid "Push Notifications"
msgstr "Notificações Push"

#: push_notifications/exc.py:11
#, python-brace-format
msgid "Invalid notification token, {reason}"
msgstr "Token de notificação inválido, {reason}"

#: push_notifications/models.py:17 users/models.py:197
msgid "user"
msgstr "usuário"

#: push_notifications/models.py:35
msgid "kind"
msgstr "espécie"

#: push_notifications/models.py:36
msgid "The kind of notification"
msgstr "A espécie de notificação"

#: push_notifications/models.py:41
msgid "title"
msgstr "título"

#: push_notifications/models.py:42
msgid "This is the text that shows on the top of the notification"
msgstr "Este é o texto que aparece no topo da notificação"

#: push_notifications/models.py:46
msgid "description"
msgstr "descrição"

#: push_notifications/models.py:47
msgid "This is the text that contains the details of the notification"
msgstr "Este é o texto que contém os detalhes da notificação"

#: push_notifications/models.py:51
msgid "additional data"
msgstr "dados adicionais"

#: push_notifications/models.py:52
msgid "The additional data that is sent with the notification"
msgstr "Os dados adicionais enviados com esta notificação"

#: push_notifications/models.py:56
msgid "status"
msgstr "situação"

#: push_notifications/models.py:57
msgid "The current status of this notification"
msgstr "A situação atual desta notificação"

#: push_notifications/models.py:62
msgid "receipt ID"
msgstr "ID recibo"

#: push_notifications/models.py:64
msgid ""
"The notification service ID for this notification, with this receipt ID we "
"can check if the message was delivered"
msgstr ""
"O ID da notificação no serviço de notificação, com este ID do recibo podemos "
"verificar se a mensagem foi entregue"

#: push_notifications/models.py:72
msgid "delivery attempts"
msgstr "tentativas de entrega"

#: push_notifications/models.py:73
msgid "How many times we tried to deliver this notification"
msgstr "Quantas vezes tentamos entregar esta notificação"

#: push_notifications/models.py:78
msgid "failure kind"
msgstr "espécie falha"

#: push_notifications/models.py:79
msgid "When the notification fails this was the reason provided"
msgstr "Quando esta notificação falhou esse o motivo fornecido"

#: push_notifications/models.py:86
msgid "failure message"
msgstr "mensagem de falha"

#: push_notifications/models.py:87
msgid "The message provided of the cause of the failure"
msgstr "A mensagem fornecida com a causa da falha"

#: push_notifications/models.py:93
msgid "read at"
msgstr "lido(a) em"

#: push_notifications/models.py:94
msgid ""
"The exact time that this notification was marked as read by the end-user"
msgstr ""
"O momento exato que esta notificação foi marcada como lida pelo usuário final"

#: push_notifications/models.py:99
msgid "delivery confirmation received at"
msgstr "confirmação de entrega recebida em"

#: push_notifications/models.py:101
msgid ""
"When the provider of this notification confirmed the delivery of this "
"notification"
msgstr ""
"Quando o fornecedor desta notificação confirmou a entrega desta notificação"

#: push_notifications/models.py:108
msgid "push notification"
msgstr "notificação Push"

#: push_notifications/models.py:109
msgid "push notifications"
msgstr "notificações Push"

#: push_notifications/services.py:255
msgid "it may not be blank"
msgstr "não pode ser vazio"

#: push_notifications/services.py:259
msgid "value too big"
msgstr "Valor muito grande"

#: users/admin.py:34
msgid "Permissions"
msgstr "Permissões"

#: users/admin.py:45
msgid "Preferences"
msgstr "Preferências"

#: users/apps.py:8
msgid "User"
msgstr "Usuário"

#: users/apps.py:9
msgid "Users"
msgstr "Usuários"

#: users/models.py:88
msgid "is staff"
msgstr "é da equipe interna"

#: users/models.py:89
msgid "Only staff users can access the admin"
msgstr "Apenas usuários da equipe interna podem acessar o admin"

#: users/models.py:93
msgid "is admin"
msgstr "é super usuário"

#: users/models.py:94
msgid "Super users have all permissions"
msgstr "Super usuários tem todas as permissões"

#: users/models.py:151
msgid "email address"
msgstr "endereço email"

#: users/models.py:152
msgid "full name"
msgstr "nome completo"

#: users/models.py:154
msgid "notification token"
msgstr "token notificação"

#: users/models.py:155
msgid "The token used to send push notifications to the user's phone"
msgstr "O token utilizado para enviar notificações push ao telefone do usuário"

#: users/models.py:161
msgid "preference language"
msgstr "idioma preferência"

#: users/models.py:167
msgid "preference time zone"
msgstr "fuso horário preferência"

#: users/models.py:173
msgid "is active"
msgstr "está ativo"

#: users/models.py:174
msgid "Inactive users can't login. Use this instead of deleting the user."
msgstr ""
"Usuário inativos não podem fazer login. Use isto em vez de excluir o usuário."

#: users/models.py:178
msgid "date joined"
msgstr "data inscrição"

#: users/models.py:198
msgid "users"
msgstr "usuários"

#: users/models.py:207
msgid "user group"
msgstr "grupo de Usuário"

#: users/models.py:208
msgid "user groups"
msgstr "grupo de Usuários"

#: users/services/auth.py:11
#, python-brace-format
msgid "The '{username}' account was not found or is inactive"
msgstr "A conta '{username}' não foi encontrada ou está inativa"

#: users/services/auth.py:16
#, python-brace-format
msgid "Invalid password for '{username}' account"
msgstr "Senha inválida para a conta '{username}'"

#: users/services/auth.py:24 users/services/auth.py:40
msgid "Please pick another account"
msgstr "Por favor selecione outra conta"

#: users/services/auth.py:30
msgid "Password mismatch, passwords are case-sensitive"
msgstr "Senhas não conferem, senhas são sensíveis a maiúsculas/minúsculas"
